%YAML 1.2
---
Application:
    wake_interval: 5

Daemon:
    user: daemon
    group: daemon
    pidfile: /var/run/myapp.pid

Logging:
  formatters:
    verbose: '%(levelname) -10s %(asctime)s %(process)-6d %(processName) -15s %(name) -10s %(funcName) -20s: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: verbose
      level: DEBUG
  loggers:
    MyApp:
      handlers: [console, file]
      level: DEBUG
      propagate: true
