%YAML 1.2
---
Application:
    wake_interval: 5

Daemon:
    user: daemon
    group: daemon
    pidfile: /var/run/myapp.pid

Logging:
  version: 1
  formatters:
    verbose:
      format: '%(levelname) -10s %(asctime)s %(process)-6d %(processName) -15s %(name) -10s %(funcName) -20s: %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: verbose
      level: DEBUG
      debug_only: True
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: verbose
      level: DEBUG
      filename: example.log
      maxBytes: 1024
      backupCount: 3
  loggers:
    MyApp:
      handlers: [console, file]
      level: DEBUG
      propagate: true
    clihelper:
      handlers: [console, file]
      level: DEBUG
      propagate: true
  disable_existing_loggers: false
  incremental: false

