language: python
python:
    - 2.6
    - 2.7
    - pypy
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors unittest2; fi
    - "pip install -r requires.txt --use-mirrors"
script: nosetests
